# Site settings
title: Ipad Mini Apple 16 Gb Wifi Led 7.9 - $ 4799,99 en MercadoLibre
email: perrro@gmail.com
description: Ipad Mini Apple 16 Gb Wifi Led 7.9 - $ 4799,99 en MercadoLibre
baseurl: "/repositorio" # the subpath of your site, e.g. /blog/
url: "http://perrro.github.io" # the base hostname & protocol for your site


twitter_username: perrro
github_username:  perrro

# Build settings
markdown: kramdown
